# Generated by Django 3.1.1 on 2021-05-15 10:32

import django.contrib.auth.mixins
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmnetcarname', models.CharField(default='Null', max_length=30)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('carinstace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.cars')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.user')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customeruser')),
            ],
            options={
                'ordering': ['date'],
                'permissions': [('view_appointments', 'Can View Appointments')],
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model),
        ),
    ]
