# Generated by Django 3.1.1 on 2021-05-15 10:32

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('carname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('carprice', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('compuser', models.CharField(default='', max_length=20)),
                ('companyslug', models.SlugField(allow_unicode=True, null=True)),
                ('photo', models.ImageField(upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('myshowroom', models.CharField(default='', max_length=20)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailcarname', models.CharField(default='Null', max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('carprice', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('compuser', models.CharField(default='', max_length=20)),
                ('companyslug', models.SlugField(allow_unicode=True, null=True)),
                ('milege', models.FloatField()),
                ('seating', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='Petrol', max_length=8)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=10)),
                ('airbags', models.IntegerField()),
                ('photo1', models.ImageField(default='path/to/my/default/image.jpg', upload_to='cars/')),
                ('photo2', models.ImageField(default='path/to/my/default/image.jpg', upload_to='cars/')),
                ('photo3', models.ImageField(default='path/to/my/default/image.jpg', upload_to='cars/')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.cars')),
            ],
        ),
    ]
